# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-19 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awewards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(blank=True, max_length=50)),
                ('project_photo', models.ImageField(upload_to='projectpics/')),
                ('description', models.TextField(blank=True)),
                ('github_repo', models.CharField(blank=True, max_length=200)),
                ('url', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
